<?php
$page_title = "A New Era of Supersonic Flight";
$image_path = "story3.jpg"; // Image path
$back_link = "Mainpage.php"; // Link to navigate back
$story_content = "
    In 2035, the aviation industry was on the brink of a new revolution, and it all began with Sonic Aero, a company dedicated to making supersonic travel mainstream once again. The dream of crossing oceans in mere hours had always been alluring, but until now, the barriers of speed, noise, and environmental impact had kept supersonic planes grounded.

Amos Carter, a former aerospace engineer turned CEO, had always believed that the world was ready for a new era of high-speed travel. His company, Sonic Aero, had already developed prototypes for an environmentally friendly supersonic jet. Unlike the Concorde, which left a trail of sonic booms and environmental damage in its wake, the new Sonic One was designed to eliminate noise pollution while using biofuels to cut carbon emissions.

Amos and his team worked relentlessly, overcoming technical challenges such as streamlining the jet's shape and fine-tuning its engines. The breakthrough came when they developed a unique propulsion system that reduced the shockwave generated by supersonic speeds, allowing the plane to fly faster than the speed of sound without the disruptive boom.

On the day of the first transatlantic test flight, Sonic Aero's headquarters in Seattle buzzed with excitement. The plane, a gleaming silver jet, looked like something out of a sci-fi film. As it took off, crossing the U.S. in just under three hours, the skies seemed to welcome it, moving effortlessly through the air. The flight was flawless, proving that not only could supersonic flight be quiet and eco-friendly, but it could also change the way the world traveled.

As the years passed, Sonic Aero's supersonic jets became the preferred method of travel for business executives, tourists, and even governments, drastically cutting flight times and making long-haul travel more efficient. Airlines around the world integrated the Sonic One into their fleets, and what was once a dream became the new standard in air travel.

Amos Carter's vision of a faster, quieter, and greener world took flight in the 2030s, proving that when innovation meets sustainability, the skies are not the limit—they are just the beginning.";
$back_link = "Mainpage.html";
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $page_title; ?></title> 
    <style>
        body {
            margin: 0;
            font-family: 'Georgia', serif;
            background-color: #050300;
            color: #fff1e3;
            padding: 20px;
        }
        h1 {
            text-align: center;
            color: #fff0e1;
            margin-bottom: 20px;
        }
        .content {
            max-width: 800px;
            margin: 0 auto;
            line-height: 1.6;
        }
        .story-image {
            display: block;
            max-width: 100%;
            margin: 20px auto;
            border: 5px solid #e9c85c9a;
            border-radius: 10px;
        }
        a.back {
            display: block;
            text-align: center;
            margin-top: 30px;
            text-decoration: none;
            color: #fff1e3;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1><?php echo $page_title; ?></h1>
    <div class="content">
        <img src="<?php echo $image_path; ?>" alt="Story Image 1" class="story-image"> 
        <p><?php echo $story_content; ?></p> 
    </div>
    <a href="<?php echo $back_link; ?>" class="back">← Back to Doors</a> 
</body>
</html>
